package Threads;

public class ResultTask extends Thread{
    public void run(){
        System.out.println("Result generated by: "+Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1=new ResultTask();
                t1.run();//Normal Execution -> Always the main thread
                t1.start();//Multi Threading ->T-0,T-1, & so on
        //⭐start internally calls run()
        //⭐we cant start a thread twice
    }
}
